### PR TITLE
Add HotJar

### PR DESCRIPTION
**Pull request by corysimmons**
~~Don't merge yet.~~ Merge after review please.

### CODE REVIEW

**Comment by corysimmons** [comment]
@siddharthlatest Review please. :bow:

**Comment by siddharthlatest** [comment]
@corysimmons Would the same tracking code work? I had created this one for only reactivsearch/ prefix URLs.

**Comment by corysimmons** [comment]
We can change it to `appbase.io`, but I'm not sure it'd do the same recording and such. I can look into it tomorrow.

**Review by metagrover — CHANGES_REQUESTED** [review]
Hey cory! You needn't build the playground storybook. We directly deploy it on gh-pages.

Can you send-in another PR with just the HotJar changes and while you're at it, you can remove the build command from package.json as well.

**Comment by corysimmons** [comment]
@metagrover Yeah let me double check with HotJar on which tracking code to use then I'll submit another one.

**Pull request closed without merging**
